language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t jajacontainer/docker-react -f Dockerfile.dev

script:
  - docker run -e CI=true jajacontainer/docker-react npm run test -- --coverage
